Pre-Processing

In [ ]:
from __future__ import division
import gensim
import glob
from sklearn.decomposition import PCA
import gensim.models.word2vec
from collections import Counter
from sklearn.metrics.pairwise import cosine_similarity
import itertools
import nltk
from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize
import re
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer
from string import punctuation
import csv

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
f1 = open("input.txt","r")
fname = f1.read()
print(fname)

TestFile.txt


In [ ]:

def Pre_process(text,i ,remove_stopwords=True, stem_words=True):
    # Clean the text, with the option to remove stopwords and to stem words.

    # Convert words to lower case and split them
    text = text.split()
    # Optionally, remove stop words
    if remove_stopwords:
        stops = set(stopwords.words("english"))
        text = [w for w in text if not w in stops]

    text = " ".join(text)
    if i==0:
      print("------After removing stop words-----")
      print(text)
    # Clean the text
    text = re.sub(r"[^A-Za-z0-9^,.!\/'+-=]", " ", text)
    text = re.sub(r"what's", "what is ", text)
    text = re.sub(r"\'s", " ", text)
    text = re.sub(r"\'ve", " have ", text)
    text = re.sub(r"can't", "cannot ", text)
    text = re.sub(r"n't", " not ", text)
    text = re.sub(r"i'm", "i am ", text)
    text = re.sub(r"\'re", " are ", text)
    text = re.sub(r"\'d", " would ", text)
    text = re.sub(r"\'ll", " will ", text)
    text = re.sub(r",", "", text)
#    text = re.sub(r"\.", " ", text)
    text = re.sub(r"!", "", text)
    text = re.sub(r"\;", "", text)
    text = re.sub(r"\[", "", text)
    text = re.sub(r"\.", "", text)
    text = re.sub(r"\/", "", text)
    text = re.sub(r"\]", "", text)
    text = re.sub(r"\^", "", text)
    text = re.sub(r"\+", "", text)

    text = re.sub(r"\-", "", text)
    text = re.sub(r"\=", "", text)
    text = re.sub(r"'", "", text)
    text = re.sub(r"(\d+)(k)", r"\g<1>000", text)
    text = re.sub(r":", " : ", text)
    text = re.sub(r" e g ", " eg ", text)
    text = re.sub(r" b g ", " bg ", text)
    text = re.sub(r" u s ", " american ", text)
    text = re.sub(r"\0s", "0", text)
    text = re.sub(r" 9 11 ", "911", text)
    text = re.sub(r"e - mail", "email", text)
    text = re.sub(r"\s{2,}", " ", text)
    text = re.sub(r"\d{1,5}"," " ,text)
    if i==0:
      print("------After removing Special characters-----")
      print(text)
    # Optionally, shorten words to their stems
    if stem_words:
        text = text.split()
        stemmer = SnowballStemmer('english')
        stemmed_words = [stemmer.stem(word) for word in text]
        text = " ".join(stemmed_words)
    if i==0:
      print("-----After stemming------")
      print(text)

    # Return a list of words
    return(text)





f2 = open(fname,"r")
lines = f2.read()
print("----The file is here----")
print()
print(lines)
print()
lines = lines.split('.')
print("-----After sentence Tokenization------")
print()
print(lines)

# Do pre-processing for each line
i=0
sent_list = []
org_sent_list = []
for line in lines:
  if len(line)== 0:
    continue
  org_sent_list.append(line)
  line = Pre_process(line,i)
  i=i+1
  sent_list.append(line)
#print(sent_list)


----The file is here----

The usual incubation period (the time between infection and symptom onset) ranges from one to 14 days, and is most commonly five days..
Some infected people have no symptoms, known as asymptomatic or presymptomatic carriers; transmission from such a carrier is considered possible. COVID-19 can be provisionally diagnosed on the basis of symptoms and confirmed using reverse transcription polymerase chain reaction (RT-PCR) testing of infected secretions or CT imaging of the chest. The standard test for current infection with SARS-CoV-2 uses RNA testing of respiratory secretions collected using a nasopharyngeal swab, though it is possible to test other samples. This test uses real-time rRT-PCR which detects the presence of viral RNA fragments. Testing is often performed in automated, high-throughput centralized medical laboratories by medical laboratory scientists. Characteristic imaging features on chest radiographs and computed tomography (CT) of people who are 

In [ ]:
with open('output.csv','w', newline='') as writefile:
     writer = csv.writer(writefile)
     feild = ['Sentences']
     writer.writerow(feild)
     for sent in sent_list:
       feild = [sent]
       writer.writerow(feild)
writefile.close()


with open('org_sent.csv','w', newline='') as writefile:
     writer = csv.writer(writefile)
     feild = ['Sentences']
     writer.writerow(feild)
     for sent in org_sent_list:
       feild = [sent]
       writer.writerow(feild)
writefile.close()






Reading the sentences from csv file

In [ ]:
import csv

f = open('output.csv')
csv_f = csv.reader(f)

sent_list = []

for row in csv_f:
  sent_list.append(row[0])

print(sent_list)
print(len(sent_list))

['Sentences', 'coronavirus diseas covid infecti diseas caus sever acut respiratori syndrom coronavirus sarscov', 'it first identifi decemb wuhan china result ongo pandem', 'the first case may trace back novemb', 'as june', 'million case report across countri territori result death', 'more', 'million peopl recov', 'fever common symptom high variabl sever present older immunocompromis critic ill peopl fever', 'other common symptom includ cough loss appetit fatigu short breath sputum product muscl joint pain', 'symptom nausea vomit diarrhoea observ vari percentag', 'less common symptom includ sneez runni nose sore throat skin lesion', 'some case china initi present chest tight palpit', 'a decreas sens smell disturb tast may occur', 'loss smell present symptom confirm case south korea', 'as common infect delay moment person first infect time develop symptom', 'this call incub period', 'covid spread primarili peopl close contact one person inhal small droplet produc infect person symptomat 

In [ ]:
!pip install "tensorflow_hub>=0.6.0"

In [ ]:
import tensorflow as tf
import numpy as np
import tensorflow_hub as hub
url = "https://tfhub.dev/google/universal-sentence-encoder-large/3"
# Import the Universal Sentence Encoder's TF Hub module
embed = hub.KerasLayer(url)

# Compute a representation for each message, showing various lengths supported.
#messages = ["That band rocks!", "That song is really cool."]



np_list = np.asarray(sent_list)
tensor_list = tf.convert_to_tensor(np_list)
print(np_list)
inemb=embed(tensor_list)
print(inemb)

['Sentences'
 'coronavirus diseas covid infecti diseas caus sever acut respiratori syndrom coronavirus sarscov'
 'it first identifi decemb wuhan china result ongo pandem'
 'the first case may trace back novemb' 'as june'
 'million case report across countri territori result death' 'more'
 'million peopl recov'
 'fever common symptom high variabl sever present older immunocompromis critic ill peopl fever'
 'other common symptom includ cough loss appetit fatigu short breath sputum product muscl joint pain'
 'symptom nausea vomit diarrhoea observ vari percentag'
 'less common symptom includ sneez runni nose sore throat skin lesion'
 'some case china initi present chest tight palpit'
 'a decreas sens smell disturb tast may occur'
 'loss smell present symptom confirm case south korea'
 'as common infect delay moment person first infect time develop symptom'
 'this call incub period'
 'covid spread primarili peopl close contact one person inhal small droplet produc infect person symptomat no

In [ ]:
from numpy import array
import tensorflow as tf
from keras.layers import LSTM
from keras.models import Sequential
from keras.layers import RepeatVector
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding
from keras.layers import TimeDistributed
from keras.utils import plot_model
from keras.layers import Bidirectional

doc=array(inemb)
do=doc.reshape(1,40,512)

#print('shape of do'),
#print(do.shape)

model = tf.keras.Sequential()
#model.add(tf.keras.layers.Embedding(vocab_size, 8, input_length=25))
model.add(tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(25, return_sequences=True), input_shape=(100,512)))
model.add(tf.keras.layers.TimeDistributed(tf.keras.layers.Dense(1)))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
model.fit(do, do, epochs=10,batch_size=1,verbose=0)
yhat = model.predict(do, verbose=0)
print(yhat[0,:,0])
#print('Accuracy: %f' % (accuracy*100))

[-0.17258425 -0.25455752 -0.27843952 -0.27323115 -0.29208732 -0.33378544
 -0.2970642  -0.33717033 -0.38534698 -0.40562776 -0.41867015 -0.44885612
 -0.42474267 -0.3895083  -0.40221056 -0.38938153 -0.36234242 -0.38519284
 -0.33163795 -0.3458007  -0.36819744 -0.3882267  -0.39844972 -0.4260376
 -0.38815364 -0.3977092  -0.4090575  -0.40394944 -0.39248928 -0.42137873
 -0.3985904  -0.3715169  -0.36715403 -0.39301842 -0.39993328 -0.37690672
 -0.35402313 -0.33591512 -0.3273979  -0.2811273 ]


In [ ]:
import numpy as np

new=yhat[0,:,0]
new1=new.tolist()
i=0
list=[]
length=len(new1)
while(i!=length):
  list.append(new[i])
  j=0
  while(j!=100):
      list.append(0)
      j=j+1
  i=i+1
print(len(list))


arr=np.array(list)
arr1=np.reshape((arr),(40,41))
print(arr1)




In [ ]:
from numpy import array
from sklearn.decomposition import TruncatedSVD
# svd
svd = TruncatedSVD(n_components=100)
svd.fit(arr1)
new = svd.transform(arr1)
print(new)

[[2.99977303e-01 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 2.98528526e-17]
 [3.31930161e-01 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 3.30327064e-17]
 [3.79919469e-01 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 3.78084603e-17]
 ...
 [3.46330583e-01 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 3.44657938e-17]
 [3.59654784e-01 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 3.57917788e-17]
 [3.09229255e-01 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 3.07735795e-17]]


In [ ]:
from scipy.ndimage import gaussian_filter

new1=gaussian_filter(new,sigma=1)
print(new1)
print(len(new1))




[[2.01669607e-01 9.31272691e-02 1.83833157e-02 ... 1.82945313e-18
  9.26774998e-18 2.00695619e-17]
 [2.17412173e-01 1.00396893e-01 1.98183389e-02 ... 1.97226239e-18
  9.99120141e-18 2.16362155e-17]
 [2.41453642e-01 1.11498796e-01 2.20098537e-02 ... 2.19035545e-18
  1.10960299e-17 2.40287513e-17]
 ...
 [2.33309166e-01 1.07737828e-01 2.12674389e-02 ... 2.11647253e-18
  1.07217495e-17 2.32182371e-17]
 [2.20412093e-01 1.01782200e-01 2.00917985e-02 ... 1.99947627e-18
  1.01290631e-17 2.19347587e-17]
 [2.09417770e-01 9.67052266e-02 1.90896042e-02 ... 1.89974087e-18
  9.62381771e-18 2.08406362e-17]]
100


In [ ]:
import numpy as np
def cos_sim(a, b):
	"""Takes 2 vectors a, b and returns the cosine similarity according
	  to the definition of the dot product
	"""

	dot_product = np.dot(a, b)
	norm_a = np.linalg.norm(a)
	norm_b = np.linalg.norm(b)
	return dot_product / (norm_a * norm_b)


list1=[]
i=0
j=1
while(j!=length):
	p=cos_sim(new1[i],new1[j])
	i=i+1
	j=j+1
	list1.append(p)
print(list1)
length=len(list1)
i=0
while(i!=length):
	if(list1[i]<1):
		a=i

		print(a)
	i=i+1



[1.0, 1.0000000000000002, 1.0000000000000002, 0.9999999999999999, 0.9999999999999999, 0.9999999999999999, 0.9999999999999999, 1.0000000000000002, 1.0000000000000002, 1.0000000000000002, 0.9999999999999999, 1.0, 1.0000000000000002, 1.0, 1.0000000000000002, 1.0000000000000002, 1.0000000000000002, 1.0, 1.0, 1.0, 1.0, 1.0000000000000002, 1.0000000000000002, 1.0, 0.9999999999999998, 1.0, 1.0, 1.0, 1.0, 1.0, 0.9999999999999998, 0.9999999999999998, 0.9999999999999998, 1.0, 0.9999999999999998, 0.9999999999999998, 1.0000000000000002, 1.0000000000000002, 1.0000000000000002, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0000000000000002, 0.9999999999999999, 0.9999999999999999, 1.0000000000000002, 1.0, 1.0, 1.0000000000000002, 0.9999999999999999, 1.0000000000000002, 1.0, 1.0, 0.9999999999999999, 1.0, 1.0, 1.0000000000000002, 1.0, 1.0, 1.0000000000000002, 1.0000000000000002, 1.0, 0.9999999999999999, 1.0, 1.0000000000000002, 1.0000000000000002, 1.0, 0.9999999999999997, 0.9999999999999999, 1.0, 1.0, 1.0, 0.9999999

In [ ]:
if(list1[0]<1.0):
  print(list1[0])
i=0
j=1
length=len(list1)
while(j!=length):
  a=list1[i]*list1[j]
  b=a**0.5
  if(b<1.0):
    print(i)
  i=i+1
  j=j+1
if(list1[length-1]<1.0):
  print(list1[length-1])

3
4
5
10
23
24
29
30
31
32
33
34
46
55
56
64
65
69
70
71
74
75
76
78
91
92
94
95
96


**READING FROM CSV FILE**

In [ ]:
import tensorflow as tf
import numpy as np
from sklearn.decomposition import PCA
import gensim.models.word2vec
from collections import Counter
from sklearn.metrics.pairwise import cosine_similarity
import itertools
import nltk
from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize
import csv
import pandas as pd
import keras
import re
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from keras.layers import Embedding
from keras.layers import Activation
from keras.callbacks.callbacks import EarlyStopping

df = pd.read_csv('usertest.csv',encoding= 'unicode_escape')
print(df[df.isnull().any(axis=1)])
df.fillna(value='',axis=0, inplace=True)
#unique_lab = df.Label.value_counts(sort=True, ascending=False)

x=df['Sentence'].values
# xm=[]
# for sent in x:
#   regex = re.compile('[^a-zA-Z]')
#   #First parameter is the replacement, second parameter is your input string
#   x1=regex.sub('', sent)
#   #Out: 'abdE'
#   xm.append(x1)
print(x);

y = df['Label'].values
ym=[]
for sent in y:
  regex = re.compile('[^a-zA-Z]')
  #First parameter is the replacement, second parameter is your input string
  y1=regex.sub('', sent)
  #Out: 'abdE'
  ym.append(y1)

# ya=np.array(ym)
# print('Shape of label tensor:',ya.shape)
# print(ya);



Empty DataFrame
Columns: [Sentence, Label]
Index: []
['The usual incubation period (the time between infection and symptom onset) ranges from one to 14 days, and is most commonly five days.'
 'Some infected people have no symptoms, known as asymptomatic or presymptomatic carriers; transmission from such a carrier is considered possible.'
 'Symptoms of COVID-19 can be relatively non-specific; the two most common symptoms are fever (88 percent) and dry cough (68 percent)'
 'Less common symptoms include fatigue, respiratory sputum production (phlegm), loss of the sense of smell, loss of taste, shortness of breath, muscle and joint pain, sore throat, headache, chills, vomiting, coughing out blood, diarrhea, and rash'
 'Among those who develop symptoms, approximately one in five may become more seriously ill and have difficulty breathing'
 'Emergency symptoms include difficulty breathing, persistent chest pain or pressure, sudden confusion, difficulty waking, and bluish face or lips; immedi

**TO FIND SENTENCE EMBEDING**

In [ ]:
import tensorflow as tf
import numpy as np
import tensorflow_hub as hub
url = "https://tfhub.dev/google/universal-sentence-encoder-large/3"
# Import the Universal Sentence Encoder's TF Hub module
embed = hub.KerasLayer(url)

# Compute a representation for each message, showing various lengths supported.
#messages = ["That band rocks!", "That song is really cool."]

np_list = np.asarray(x)
tensor_list = tf.convert_to_tensor(np_list)

inemb=embed(tensor_list)
X=np.array(inemb)
print(X.shape)
print(X[1])

(50, 512)
[-0.01039853 -0.02701458  0.02882953 -0.00585437  0.06555723 -0.03763329
 -0.04561336 -0.00356026 -0.03742265  0.04771096  0.0137173   0.04241151
 -0.11555288  0.00956567  0.03220725 -0.08361451  0.02997233  0.00230015
  0.00743559  0.02679411  0.02279343  0.06722389  0.02255373  0.02715516
 -0.04772843  0.01607577  0.06695978  0.06320512 -0.02332178 -0.01966527
  0.01790928 -0.08469796 -0.02320081 -0.07860933  0.0165997   0.02297875
  0.01458892  0.0749397   0.01071396 -0.02140175 -0.02408499  0.01534618
  0.04411556 -0.01683128  0.06502429  0.01929915  0.00834309  0.00013051
  0.0547455  -0.00988404  0.03603745  0.03627491 -0.04922928  0.031744
  0.00981441  0.07191338  0.05509761  0.02794751 -0.05679391 -0.03479852
 -0.06673011 -0.04492323 -0.00097861  0.02673047 -0.09381574 -0.01935883
 -0.01870472  0.02809259 -0.03405958 -0.02587569 -0.0264174   0.00160211
  0.00578018  0.07417231  0.00491563  0.05225519 -0.04931859 -0.03379545
 -0.05547905 -0.00187482  0.00591152  0.050

**ONE HOT ENCODE LABELS**

In [ ]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
import csv
values = ya
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
 # binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
Y=array(onehot_encoded)
print(Y)
print(Y.shape)
print(Y[0])


[[0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]]
(50, 5)
[0. 0. 0. 1. 0.]


In [ ]:
#Splitting Train and Test data
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.10, random_state = 42)
print(X_train.shape,Y_train.shape)
print(X_test.shape,Y_test.shape)

(279, 512) (279, 5)
(32, 512) (32, 5)


**EVALUATION**

In [ ]:
import numpy as np


Y_train=Y_train.reshape(1,279,5)
X_train=X_train.reshape(1,279,512)
X_test=X_test.reshape(1,32,512)
Y_test=Y_test.reshape(1,32,5)
for epoch in range(10):
	# fit model for one epoch on this sequence
	model.fit(X_train, Y_train, epochs=1, batch_size=1, verbose=2)
	score,acc=model.evaluate(X_test,Y_test)
	print('accuracy:',acc)

1/1 - 0s - loss: 0.1526 - accuracy: 1.0000
1/1 [==============================] - 0s 1ms/step - loss: 0.7281 - accuracy: 0.7500
accuracy: 0.75
1/1 - 0s - loss: 0.1485 - accuracy: 1.0000
1/1 [==============================] - 0s 1ms/step - loss: 0.7348 - accuracy: 0.7500
accuracy: 0.75
1/1 - 0s - loss: 0.1444 - accuracy: 1.0000
1/1 [==============================] - 0s 1ms/step - loss: 0.7315 - accuracy: 0.7500
accuracy: 0.75
1/1 - 0s - loss: 0.1406 - accuracy: 1.0000
1/1 [==============================] - 0s 1ms/step - loss: 0.7189 - accuracy: 0.7500
accuracy: 0.75
1/1 - 0s - loss: 0.1366 - accuracy: 1.0000
1/1 [==============================] - 0s 1ms/step - loss: 0.7128 - accuracy: 0.7500
accuracy: 0.75
1/1 - 0s - loss: 0.1330 - accuracy: 1.0000
1/1 [==============================] - 0s 1ms/step - loss: 0.7240 - accuracy: 0.7500
accuracy: 0.75
1/1 - 0s - loss: 0.1293 - accuracy: 1.0000
1/1 [==============================] - 0s 1ms/step - loss: 0.7327 - accuracy: 0.7500
accuracy: 0.75

In [ ]:
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from keras.layers import RepeatVector
from keras.layers import TimeDistributed
from keras.utils import plot_model
from keras.layers import Bidirectional
Y_train=Y_train.reshape(1,279,5)
# doc=array(inemb)
# do=doc.reshape(1,100,512)
X_train=X_train.reshape(1,279,512)
model = tf.keras.Sequential()
model.add(tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(150,return_sequences=True), input_shape=(279,512)))
#model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.TimeDistributed(tf.keras.layers.Dense(5, activation='softmax')))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
#train LSTM
#
# for i in range(345):
# 	print('Expected:', y[0, i], 'Predicted', yhat[0, i])
# 	print(label_encoder.inverse_transform(yhat[0,i]))

**PREDICTION AND WRITING TO OUTPUT FILE**

In [ ]:
import np
import numpy
#loaded_model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
X=X.reshape(1,50,512)
Y=Y.reshape(1,50,5)
yhat = model.predict(X, verbose=0)
sentd={}
for i in range(50):
  print('Expected:', Y[0, i], 'Predicted', yhat[0, i])
  prob=np.array(yhat[0, i])
  labels=np.eye(5,dtype=int)[np.argmax(yhat[0, i],axis=-1)]
  inverted = label_encoder.inverse_transform([argmax(labels)])
  print(labels)
  print(inverted)
  lab=numpy.array_str(inverted)
  s=numpy.array_str(X[0,i])
  sentd[x[i]]=lab
val=[' ']

f2=open("out.txt","w+")

for value in sentd.values():
  flag=0
  #print('value:',value)
  for v in val:
    #print('v:',v)
    if(value==v):
      flag=1
  if(flag==0):
    #print('hi')
    val.append(value)


# for j in val:
#   print('j=',j)
for n in val:
  #print(n)
  f2.write(n)
  f2.write(":")
  for k in sentd.keys():
    if(sentd[k]==n):
      f2.write(k)
      #print(k)
      f2.write(".\n")
f2.close()

Expected: [0. 0. 0. 1. 0.] Predicted [9.9210489e-01 5.2981963e-04 3.8961248e-04 6.9575268e-03 1.8266657e-05]
[1 0 0 0 0]
['Diagnosis']
Expected: [0. 0. 0. 1. 0.] Predicted [9.9073225e-01 4.8607055e-04 5.9144397e-04 8.1329951e-03 5.7143036e-05]
[1 0 0 0 0]
['Diagnosis']
Expected: [0. 0. 0. 1. 0.] Predicted [2.2233413e-01 2.8683797e-03 1.3029855e-03 7.7342337e-01 7.1100876e-05]
[0 0 0 1 0]
['Symptoms']
Expected: [0. 0. 0. 1. 0.] Predicted [1.52535615e-02 6.28103316e-03 1.21836970e-03 9.77140784e-01
 1.06252584e-04]
[0 0 0 1 0]
['Symptoms']
Expected: [0. 0. 0. 1. 0.] Predicted [1.0521208e-02 1.5540931e-02 6.2369872e-03 9.6704829e-01 6.5257674e-04]
[0 0 0 1 0]
['Symptoms']
Expected: [0. 0. 0. 1. 0.] Predicted [0.09701185 0.0330663  0.00308554 0.86521214 0.00162416]
[0 0 0 1 0]
['Symptoms']
Expected: [0. 0. 0. 1. 0.] Predicted [0.06471919 0.8604062  0.00937249 0.04651278 0.0189893 ]
[0 1 0 0 0]
['History']
Expected: [1. 0. 0. 0. 0.] Predicted [8.6661851e-01 1.2935096e-01 6.0526468e-04 2.772

In [ ]:
pip install np

  Created wheel for np: filename=np-1.0.2-cp36-none-any.whl size=13654 sha256=0eaaad49aa47fb9c4553772eb33bb059f8c6433a15bd79dc9de406d724f05f10
  Stored in directory: /root/.cache/pip/wheels/2b/df/57/f40bef951382112d9c644b3ec6d713ceb200ea7c15c074de42
Successfully built np


**PREDICTION AND WRITING TO OUTPUT FILE**

In [ ]:

import numpy  as np

X=X.reshape(1,50,512)
Y=Y.reshape(1,50,5)
yhat = model.predict(X, verbose=0)
sentd={}
for i in range(50):
  print('Expected:', Y[0, i], 'Predicted', yhat[0, i])
  prob=np.array(yhat[0, i])
  labels=np.eye(5,dtype=int)[np.argmax(yhat[0, i],axis=-1)]
  inverted = label_encoder.inverse_transform([argmax(labels)])
  print(labels)
  print(inverted)
  lab=np.array_str(inverted)
  s=np.array_str(X[0,i])
  sentd[x[i]]=lab
val=[' ']

f2=open("out.txt","w+")
for value in sentd.values():
  flag=0
  for v in val:
    if(value==v):
      flag=1
  if(flag==0):
    val.append(value)

for n in val:
  f2.write(n)
  f2.write(":")
  for k in sentd.keys():
    if(sentd[k]==n):
      f2.write(k)
      f2.write(".\n")
f2.close()